### ISSUE TITLE
LINK: fatal error LNK1104: can't open the file"nvdiffrast_plugin.pyd"

### ISSUE THREAD

**Issue by xiaomihefeifei** [NVlabs/nvdiffrast#100]
I was able to use version 0.28 before. But, it seems like meet a compile error when I try use version  0.30. 
![image](https://user-images.githubusercontent.com/25178324/205014435-783b1c0c-d1ba-4976-826b-100af8d16acf.png)

Thank you very much for any suggestionl.

**Comment by s-laine** [comment]
This looks like a ninja build issue and isn't necessarily related to the nvdiffrast version change. The error could be caused by the library being in use while you're trying to compile a new version. If that's not the case here, you should try clearing torch's extension build directory for nvdiffrast, in case it's in some sort of corrupted state.

The directory is easiest to locate by seeing what `torch.utils.cpp_extension._get_build_directory('nvdiffrast_plugin', False)` returns. On Windows it's probably somewhere under ` %localappdata%\torch_extensions` by default.

**Comment by xiaomihefeifei** [comment]
Thank you very much for helping me I solved this problem perfectly.
