### ISSUE TITLE
silhouette loss possibility

### ISSUE THREAD

**Issue by esx2ve** [NVlabs/nvdiffrast#14]
Hello and thank you for releasing this amazing library!

I'm experimenting with implementations of different approaches to joint geometry optimization and inverse rendering, and I've tried implementing a sillhouette (mask) loss approach. Geometry optimization with texture works very well, but when I input a _ones_ tensor into the texturing step and compare against the alpha mask of the input (synthetic data, so I have ground truth mask), no gradient seems to flow into the vertices (or anywhere). I also tried differentiable gaussian blur and it didn't seem to help. Is it in principle possible, or am I completely off road trying this?

Thank you!

**Comment by s-laine** [comment]
Hi @esx2ve! Are you executing the antialiasing op before computing the loss? If not, there will be no coverage-related gradients flowing into vertex positions because the coverage is point sampled and discontinuous. The antialiasing step creates a continuous relationship between vertex positions and colors of silhouette pixels, enabling gradient flow. If you see no gradients despite using the antialiasing op, please send a simple test case that reproduces the problem.

**Comment by esx2ve** [comment]
Hello @s-laine, thank you for the promt reply!

I've located the problem - I've been masking the resulting image _after_ the antialiasing. Once I've moved it _before_ the antialiasing step, everything works!
