### ISSUE TITLE
Runtime cuda error

### ISSUE THREAD

**Issue by MHassan1122** [NVlabs/nvdiffrast#167]
RuntimeError                              Traceback (most recent call last)
Cell In[16], line 3
      1 camera = render.get_rotate_camera(0)
      2 f, ax = plt.subplots(1, 2)
----> 3 output = render.render_mesh(init_mesh, camera, [512, 512], return_types=['normals'])
      4 ax[0].imshow(((output['normals'][0] + 1) / 2.).cpu().detach())
      5 output = render.render_mesh(gt_mesh, camera, [512, 512], return_types=['normals'])

File ~\FlexiCubes\examples\render.py:91, in render_mesh(mesh, camera, iter_res, return_types, white_bg, wireframe_thickness)
     88 vertices_clip = (proj @ homogeneous_vecs.unsqueeze(-1)).squeeze(-1)
     89 faces_int = mesh.faces.int()
---**> **_91 rast, _ = dr.rasterize(_****
     92     glctx, vertices_clip, faces_int, iter_res)
     94 out_dict = {}
     95 for type in return_types:

RuntimeError: Cuda error: 400[cudaGraphicsMapResources(2, &s.cudaPosBuffer, stream);]
i wonder that i correctly installed and import as see in the render.py 
import nvdiffrast.torch as dr
so when i want to run my program it seems some errors 
can any one know about this 
![cuda error](https://github.com/NVlabs/nvdiffrast/assets/125865702/c2507d7d-47fb-4a5a-88c0-f78b1b64bbaa)

**Comment by s-laine** [comment]
This looks like a Cuda or graphics driver issue, so updating both to the latest versions may help.

If you cannot get the OpenGL rasterizer working, you may try using the Cuda-based rasterizer as discussed in the documentation [here](https://nvlabs.github.io/nvdiffrast/#rasterizing-with-cuda-vs-opengl-new), i.e., create the rasterization context as type `dr.RasterizeCudaContext` instead of `dr.RasterizeGLContext`.
