### ISSUE TITLE
Wrong scene rasterization

### ISSUE THREAD

**Issue by csyhping** [NVlabs/nvdiffrast#180]
Hi @s-laine , I tried your suggestion about rendering multiple objects, as you mentioned before, but I still need help to get the correct result.  Could you please kindly help me about this, I'm not sure where is wrong.

**Comment by s-laine** [comment]
Do I understand correctly that you're trying to reconstruct a 3D mesh for an isolated object from a single image? I don't think that's going to be possible; the task is much too ambiguous unless you had extremely strong, differentiable priors to penalize solutions that should be considered invalid. This kind of reconstruction benefits greatly from having a large set of reference images with known camera positions and segmented-out backgrounds, and it is still not easy. See [nvdiffrec](https://nvlabs.github.io/nvdiffrec/) for one such solution.

**Comment by s-laine** [comment]
Ok, thanks for the clarification. The problem is the camera model, or rather, the lack of one. You are dividing the vertices' x and y coordinates with z, and then replacing all w coordinates with 1.0 without applying any sort of projection. This turns the model into a flat plane, and the depth test in the rasterizer cannot distinguish which triangles should be in front and which in back.

I don't understand how the camera is supposed to work, but your code suggests that the vertices' z coordinate is actually post-projection w coordinate, and the correct pixel positions are obtained by just dividing x and y by that. Here's a hacky way to reconstruct a z coordinate that can be used for depth test:
```python
vert_cam = torch.mm(pos, K.t())
vert_ndc_new = torch.mm(vert_cam, N.t())
pos = torch.cat([vert_ndc_new, pos[:, 2:3].square()], axis=1)[:, [0, 1, 3, 2]].unsqueeze(0)
```
Here the post-perspective w coordinate is taken to be just the z coordinate of the input, and a new z coordinate is created by squaring that value, so that after the perspective divide the depth values end up in the range they were in the mesh. If this falls outside -1 ... +1 range, there will be depth clipping, and you need to scale the values accordingly.

The proper way to do this would be appending the w=1.0 coordinate to the input vertex positions and multiplying them with a 4&times;4 perspective projection matrix (as well as other necessary transformations), creating homogeneous vertex positions that nvdiffrast expects as inputs. But this requires knowing what the view frustum is supposed to be, and now this seems to be somehow baked into the vertex positions of the model.

**Comment by s-laine** [comment]
If dividing by z is the correct thing to do, that corresponds to a camera whose frustum opens at a 90 degree angle. This corresponds to setting `x` equal to `n` in `projection()` function in `samples/torch/util.py`. If `K` is a 2D post-projective transformation to the image, you can formulate it as a 4&times;4 matrix and multiply by that after the perspective transformation.
