### ISSUE TITLE
how to render several polygons into a single image ?

### ISSUE THREAD

**Issue by lith0613** [NVlabs/nvdiffrast#73]
Hi, thanks for your wondeful work !  I have several polygons, and each polygon has a different texture map, and I want to render them into a image together, how can I do this in nvdiffrast ?  For example, I upload two mesh with diffrent texture, and how can I render these two mesh into a single image, so that they can have different colors ?
[data.zip](https://github.com/NVlabs/nvdiffrast/files/8460705/data.zip)

**Comment by lith0613** [comment]
> At the moment there is no support for accessing multiple individual textures in the texture op. The most efficient workaround is to place all textures into a single texture atlas and modify the uv coordinates for each mesh to point to the correct one. This has drawbacks if you need to wrap the textures or mipmap them, as the individual textures can blend together at the texture edges. To mitigate this, it helps to pad each individual texture in the atlas with wrapped content.
> 
> Alternatively, if you have just a couple of meshes/textures, you can render them individually and composite them afterwards so that in each pixel you pick the closest one based on the (z/w) channel of rasterizer output.

Hi slaine, thanks for your help ! About the second method 
```
render them individually and composite them afterwards so that in each pixel you pick the closest one based on the (z/w) channel of rasterizer output. 
```
Is there a simple script for the detail implementation ? And I also wonder to know if its derivatives can be back propagation according to your suggestion ?

**Comment by lith0613** [comment]
Thanks ! I will try as your advise.

**Comment by s-laine** [comment]
Make sure you're executing the antialising op to get gradients related to the locations of the silhouette edges in the image. For correct gradients, you'd have to execute antialiasing as the very last step of the rendering pipeline, i.e., after the merging. This requires having the meshes combined into a single mesh, so in practice it's easiest to do that first, and run the entire rendering pipeline on the combined mesh.

Note that you cannot simply concatenate the triangle buffers together, but you have to offset the vertex indices in the latter meshes' triangle buffers by their start index in the vertex buffer. Otherwise the triangles in, say, the second mesh will incorrectly point to the vertices of the first mesh.
