### ISSUE TITLE
I have a bug that is fatal error: EGL/egl.h: No such file or directory. 

### ISSUE THREAD

**Issue by BIG-PIE-MILK-COW** [NVlabs/nvdiffrast#94]
I download nvdiffrast 0.3.0, and here are the errors.

[3/4] c++ -MMD -MF glutil.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /SSD_DISK/users/anaconda3/envs/get3d1/lib/python3.8/site-packages/torch/include -isystem /SSD_DISK/users/anaconda3/envs/get3d1/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /SSD_DISK/users/anaconda3/envs/get3d1/lib/python3.8/site-packages/torch/include/TH -isystem /SSD_DISK/users/anaconda3/envs/get3d1/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /SSD_DISK/users/anaconda3/envs/get3d1/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -DNVDR_TORCH -c /SSD_DISK/users/anaconda3/envs/get3d1/lib/python3.8/site-packages/nvdiffrast/common/glutil.cpp -o glutil.o 
FAILED: glutil.o 
c++ -MMD -MF glutil.o.d -DTORCH_EXTENSION_NAME=nvdiffrast_plugin_gl -DTORCH_API_INCLUDE_EXTENSION_H -DPYBIND11_COMPILER_TYPE=\"_gcc\" -DPYBIND11_STDLIB=\"_libstdcpp\" -DPYBIND11_BUILD_ABI=\"_cxxabi1011\" -isystem /SSD_DISK/users/anaconda3/envs/get3d1/lib/python3.8/site-packages/torch/include -isystem /SSD_DISK/users/anaconda3/envs/get3d1/lib/python3.8/site-packages/torch/include/torch/csrc/api/include -isystem /SSD_DISK/users/anaconda3/envs/get3d1/lib/python3.8/site-packages/torch/include/TH -isystem /SSD_DISK/users/anaconda3/envs/get3d1/lib/python3.8/site-packages/torch/include/THC -isystem /usr/local/cuda/include -isystem /SSD_DISK/users/anaconda3/envs/get3d1/include/python3.8 -D_GLIBCXX_USE_CXX11_ABI=0 -fPIC -std=c++14 -DNVDR_TORCH -c /SSD_DISK/users/qianjiachen/anaconda3/envs/get3d1/lib/python3.8/site-packages/nvdiffrast/common/glutil.cpp -o glutil.o 
In file included from /SSD_DISK/users/anaconda3/envs/get3d1/lib/python3.8/site-packages/nvdiffrast/common/glutil.cpp:14:
/SSD_DISK/users/anaconda3/envs/get3d1/lib/python3.8/site-packages/nvdiffrast/common/glutil.h:36:10: fatal error: EGL/egl.h: No such file or directory
   36 | #include <EGL/egl.h>
      |          ^~~~~~~~~~~
compilation terminated.

**Comment by s-laine** [comment]
On Linux, using the OpenGL-based rasterizer requires that you have both OpenGL and EGL installed. I suggest you take a look at our [Dockerfile](https://github.com/NVlabs/nvdiffrast/blob/main/docker/Dockerfile) to see the required libraries and environment variables, or even better, use the Docker environment directly. Note that you will also need the OS-level graphics drivers installed in the system.

Since version v0.3.0 nvdiffrast includes a Cuda-based rasterizer that doesn't require the graphics libraries or drivers. It has some restrictions compared to OpenGL (see [documentation](https://nvlabs.github.io/nvdiffrast/#rasterizing-with-cuda-vs-opengl-new)) but it could be a working solution in your use case.

**Comment by ming1993li** [comment]
Sorry, I am confused. Can you directly tell how to solve this issue?

**Comment by s-laine** [comment]
You have three options:
- Use our provided Dockerfile (what is [Docker](https://docs.docker.com/get-started/overview/)?)
- Set up your system so that it matches the configuration in the Dockerfile
- Use `RasterizeCudaContext` instead of `RasterizeGLContext` if you're ok with the [limitations](https://nvlabs.github.io/nvdiffrast/#rasterizing-with-cuda-vs-opengl-new) of the Cuda-based rasterizer

**Comment by Mofafa** [comment]
I met the same problem. But this error only appears when I connect my server using the vs code terminal... When I connect the server with my pc's terminal, it works well in the same environment. I have no idea for the reason.
